version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
           

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez 
        columns:
         - name: products_id
           description: id of products
           tests:
             - unique
             - not_null
         - name: purchase_price 
           description: prix of purchase
        
      - name: ship
        identifier: raw_gz_ship
        description: shipping information 
        columns:
          - name: orders_id
            description: id of purchase
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee of shipping 
          - name: logcost
          - name: ship_cost
